### PR TITLE
Remove concatenation from diacritics lookupList

### PR DESCRIPTION
**Pull request by iazel**
Hello,

Thank you for this library. I've noticed that the lookupList is getting concatenated over and over again, which could be relatively slow in Elm, especially for large sets and therefore I've decided to do some clean up :) 

I'm also interested to know if there is any reason to have this concatenation in the first place.

Have a nice day!

### CODE REVIEW

**Comment by kuon** [comment]
I think it was a bug in either elm test or the compiler, I don't remember exactly.

Did all tests pass with this version? I realize I don't have CI on this repository.

**Comment by iazel** [comment]
I've just run the test using elm-test version `0.19.1-revision2` and elm with version `0.19.1-3`. All 23 tests are green :)

**Comment by kuon** [comment]
Actually I had travis set up, and  travis is failing with this patch. I will update travis config.

**Comment by kuon** [comment]
I moved to github action and now everything is OK. Thanks for the patch.

**Pull request merged**
